[workspace]
resolver = "2"

members = ["crates/puzzled_core","crates/puzzled_cross","crates/puzzled_nono","crates/puzzled_nono_tui"]

[workspace.dependencies]
bitvec = "1.0.1"
clap = { version = "4.5.56", features = ["derive"] }
crossterm = { version = "0.29.0", features = ["derive-more"] }
derive_more = { version = "2.1.1", features = ["debug"] }
directories = "6.0.0"
image = "0.25.9"
miette = { version = "7.6.0", features = ["fancy"]}
ratatui = { version = "0.30.0", features = ["unstable-widget-ref"] }
rstest = "0.26.1"
serde = { version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
thiserror = "2.0.18"
toml = "0.9.11"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
tracing-test = "0.2.5"
