[package]
name = "nono-io"
version.workspace = true
edition.workspace = true

[dependencies]
image = "0.25.9"
nono = { path = "../nono"}
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tracing = "0.1.44"
